baseURL: "https://hugo-profile.netlify.app"
languageCode: "pt-br"
title: "Axl Andrade"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Axl Andrade"
  profession: "Estudante"
  github: "https://github.com/AxlAndrade"
  linkedin: "https://www.linkedin.com/in/axl-silva-de-andrade-084a7820a/"
  twitter: "https://twitter.com/axl_andrade"
  instagram: "https://instagram.com/axl_andrad18"
  facebook: "https://facebook.com/axl.andrade.16"

  # About
  disable_about: false
  descripe_l1_person: "Olá, eu sou o Axl, tento usar um pouco do meu conhecimento para tornar coisas chatas em coisas divertidas."
  descripe_l2_person: "Sou estudante de TI e de licenciatura em matemática, apaixonado por tecnologias e números."
  descripe_l3_person: "Você pode achar meus trabalhos aqui [here](#projects)"
  skills:
    - name: Python
      percentage: 70
    - name: C
      percentage: 50
    - name: HTML
      percentage: 40
    - name: CSS
      percentage: 30
    - name: Java
      percentage: 10

  # Experience
  disable_experience: true
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "Matemática"
      branch: "Licenciatura"
      university: "Universidade Federal Rural do Rio de Janeiro (IM/UFRRJ)"
      startedyear: "2020"
      graduation: "~2024"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "axlsandrade@outlook.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
